# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main


pool:
  vmImage: ubuntu-latest

steps:
- checkout: none
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 7.x
    installationPath: $(Agent.ToolsDirectory)/dotnet
- pwsh: |
    dotnet new console -f net7.0  -o ./MyTestConsole
    cd ./MyTestConsole
    dotnet build -c Release
